version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Asia/Seoul"
    groups:
      github-actions-security:
        patterns:
          - "*"
